server:
  port: 8090

spring:
  application:
    name: Capacity Request
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    # url: jdbc:postgresql://172.16.172.52:9982/postgres
    url: jdbc:postgresql://localhost:5432/nfvi
    continue-on-error: true
    jpa:
      show-sql: false
      hibernate:
        ddl-auto: update

optaplanner:
  solver:
    termination:
      spent-limit: 5s
  solver-config-xml: allocationSolutionSolverConfig.xml

logging:
  level:
    tech.scalea.capacityRequest.service: debug

app:
  capacityReserve: 0.8